Last version of pytest for pypy is 4.6.11; Also latest version pytest-cov and pytest-asyncio are not compatible with latest pytest.
https://travis-ci.org/github/syrusakbary/promise/jobs/708528307

 Could not find a version that satisfies the requirement pytest>=5.4.3 (from promise==2.3) (from versions: 2.0.0, ......... 4.6.10, 4.6.11)

https://travis-ci.org/github/syrusakbary/promise/jobs/708523881

E   AttributeError: type object 'Function' has no attribute 'from_parent'

https://travis-ci.org/github/syrusakbary/promise/jobs/708735234

pytest-cov 2.10.0 has requirement pytest>=4.6, but you'll have pytest 4.3.1 which is incompatible.